/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;

public class App {
    //Get randomNumber to get the quote
    public int getRandomNumber(int MAX) {
        Random rand = new Random();
        int randIndex = rand.nextInt(MAX);
        return randIndex;
    }

    //Function that returns the string version of quotes
    public  String getStringVersion(Quotes[] quotesFromFile, int randomNumber) {
        String printString = "";
        printString = quotesFromFile[randomNumber].author + " " + quotesFromFile[randomNumber].text;

        return printString;
    }

    //Function that gets all the Quotes when the path is passed
    public Quotes[] getQuotes(String PATH) throws  FileNotFoundException{
        Gson gson = new Gson();
        Scanner reader = new Scanner(new File(PATH));
        String stringVersion = "";

        while (reader.hasNext()) {
            String quoteString = reader.nextLine();
            stringVersion += quoteString;
        }

        Quotes[] quotesFromFile = gson.fromJson(stringVersion, Quotes[].class);
        return quotesFromFile;

    }


    //Appends quote received from online to existing json file
    public void appendQuote(String content, String PATH) throws IOException {

        Gson gson = new GsonBuilder().setPrettyPrinting().create();
        onlineQuote onlinequote = gson.fromJson(content, onlineQuote.class);
        ArrayList<String> tags = new ArrayList<>();
        Quotes quote = new Quotes(tags, onlinequote.quoteAuthor, "", onlinequote.quoteText);
        String output = gson.toJson(quote);


        Scanner reader = new Scanner(new File(PATH));
        String stringVersion = "";

        while (reader.hasNext()) {
            String quoteString = reader.nextLine();
            stringVersion += quoteString;
        }

        StringBuilder finalString = new StringBuilder(stringVersion);
        finalString.setCharAt(stringVersion.length() - 1, ',');

        BufferedWriter writer = null;
        try {
            writer = new BufferedWriter(new FileWriter("src/main/resources/recentquotes.json"));
            writer.write(finalString + output + ']');
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }


    }


    //Function to get Quotes from API request
    // It also calls the append method to add the string to the existing json file
    public void getOnlineQuotes(URL url) {
        try {
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("GET");
            System.out.println(connection.getResponseCode());

            BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            String inputLine;
            StringBuilder content = new StringBuilder();
            while ((inputLine = in.readLine()) != null) {
                content.append(inputLine);
            }
            in.close();

            System.out.println(content);
            appendQuote(content.toString(), "src/main/resources/recentquotes.json"); //append the quote

        } catch (IOException e) {
            System.out.println("Error connecting!");
        }

    }

    //add quotes if it does not exist in json file or just add all


    public static void main(String[] args) throws IOException {
        App app = new App();
        URL url = new URL("http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en");
        app.getOnlineQuotes(url);

    }

    }


